name: 04 - Using Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: 04_practice-block-using-actions/react-app   
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: List Directory Contents
        run: ls
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run Unit Tests
        run: npm  run test
        

        # 0.checkout the code from the repo 
        # 1 Install the deps of our react application 
        # 2 exccute automated tests
