name: 09 Using Functions

on:
    pull_request:
    workflow_dispatch:

jobs:
    echo1:
          runs-on: ubuntu-latest
          steps: 
              - name: Failing step
                run: exit 1 
              - name: I will be skipped 
                if: ${{success()}}
                run: echo "I will print if previous steps succeed."
              - name: I will be excute 
                if: ${{failure()}}
                run: echo "I will print if previous steps failed."  
              - name: "i will excute"
                if: ${{cancelled()}}
                run: echo "I will print if any workflow is cancelled"      
              - name: "i will excute"
                if: ${{!cancelled()}}
                run: echo "I will always print , excopet when the workflow is cancelled" 