name: Using Inputs in GitHub Actions

on: 
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Skip Deployment and only print build Output
        default: false
      target:
        type: environment
        required: true
        description: Which environment the workflow will target
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: Release from which to build and deploy

jobs:
  echo:
    runs-on: ubuntu-latest   
    steps:
      - name: Build
        run: echo "Building from tag ${{ inputs.tag }}"

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:                      
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }} using tag ${{ inputs.tag }}"
