name: 12-Using outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success    

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.set_output.outputs.status }}  # Corrected the output reference
    steps:
      - name: Print GITHUB_OUTPUT
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: build
        run: echo "status=${{ inputs['build-status'] }}" >> "$GITHUB_OUTPUT"
      - name: Set build status output
        id: set_output
        run: echo "status=${{ inputs['build-status'] }}" >> $GITHUB_ENV  # Correct output method

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the deploy job runs after the build job
    steps:
      - name: Deploy
        if: ${{ needs.build.outputs['build-status'] == 'success' }}
        run: echo "Deployment triggered"
